---
name: Suggest ideas and updates for the Docs website
about: Make a suggestions or report a problem on the docs.github.com website.
labels: engineering
body:
  - type: markdown
    attributes:
      value: |
        HUBBERS BEWARE! Please confirm you're on the github/docs-internal repo and not the github/docs repo before proceeding, unless you want to make your work public to the entire internet. The github/docs repo is open source and public to the entire internet.

        For questions, ask in Discussions: https://github.com/github/docs/discussions
  - type: checkboxes
    attributes:
      label: Contributing Guidelines
      options:
        - label: 'I agree to follow the [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)'
          required: true
        - label: 'I have read the [Contributing Guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md)'
          required: true
        - label: 'There is not a similar issue that has been [already opened](https://github.com/github/docs/issues)'
          required: true
  - type: textarea
    attributes:
      label: Suggestion
      description: What changes are you suggesting?
      placeholder: Explain, in writing, with as much detail as possible, what changes you're suggesting and why. Provide supporting information using screenshots and URLs where possible, to help us understand your suggested changes.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      placeholder: Any additional information, configuration, or data that might be necessary to reproduce the issue.
    validations:
      required: true
