trigger: remove-from-fr-board
title: Remove from FR board
description: Remove the current issue or pull request from the project board for the docs content first responder
surfaces:
  - issue
  - pull_request
  - discussion
steps:
  - type: repository_dispatch
    eventType: remove_from_FR_board
