name: Auto label Pull Requests
on:
  pull_request:

jobs:
  triage:
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@5f867a63be70efff62b767459b009290364495eb
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
