name: autoupdate branch
on:
  push:
    branches:
      - main
jobs:
  autoupdate:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}
          PR_FILTER: labelled
          PR_LABELS: autoupdate
          MERGE_MSG: "Branch was updated using the 'autoupdate branch' Actions workflow."
