# Make sure the Docker container still builds

name: Build Docker image

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  build:
    # Do not run this job for translations PRs
    if: ${{ github.ref != 'refs/heads/translations' }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Build the container
        run: docker build .
