name: Ping staging apps

# **What it does**: This keeps our staging applications from automatically spinning down.
# **Why we have it**: Staging applications can hiberate without use.
# **Who does it impact**: Anyone with a pull request in docs-internal.

on:
  schedule:
    - cron: '*/20 * * * *' # every twenty minutes

jobs:
  ping_staging_apps:
    name: Ping
    if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    env:
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: Run script
        run: script/ping-staging-apps.js
