name: Lint workflows

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches-ignore:
  #     - translations

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Run linter
        uses: cschleiden/actions-linter@43fd4e08e52ed40c0e2782dc2425694388851576
        with:
          workflows: '[".github/workflows/*.yml"]'
