name: Lint workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  lint:
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Run linter
        uses: cschleiden/actions-linter@0ff16d6ac5103cca6c92e6cbc922b646baaea5be
        with:
          workflows: '[".github/workflows/*.yml"]'
